### ISSUE TITLE
Update to Ghost 0.6.2

### ISSUE THREAD

**Issue by nibreh** [julienmalik/ghost_ynh#4]
Bonjour

Y-a-t-il possibilité de mettre à jour le script pour installer Ghost 0.6.2 (22 avril 2015) ?

Cordialement

**Comment by rgarrigue** [comment]
Bonjour

A vrai dire je m'étonne de ne pas voir la mise à jour automatique de Ghost dans l'administration ? Elle a été introduite dans la V0.4.0 normalement. De même que j'ai cherché l'onglet "about" et l'onglet "labs" ? 

En tout cas merci pour le boulot

**Comment by julienmalik** [comment]
Oui c'est possible. PR bienvenues :)
